name: eslint-tool-scan

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        working-directory: ruoyi-ui
        run: |
          npm install

      # - name: Installing JSHint
      #   working-directory: ruoyi-ui
      #   run: |
      #     sudo npm install -g jshint

      # - name: Change script permission
      #   working-directory: ruoyi-ui
      #   run: |
      #     chmod +x scripts/jshint-script.sh

      - name: Run scan with ESLint
        working-directory: ruoyi-ui
        run:  |
          npx eslint src/ --fix --format json --output-file eslint-report.json || true

      # - name: List output
      #   working-directory: ruoyi-ui
      #   run: ls -la

      - name: Archive production artifacts
        if: success() || failure()
        uses: actions/upload-artifact@v2
        with:
          name: eslint-report
          path: |
            ruoyi-ui/eslint-report.json